# ################################
# Model: CTC ASR on TIMIT with CRDNN (with LiGRU)
# Additions: TimeDomainSpecAugment
# Authors: Mirco Ravanelli & Peter Plantinga 2020
# ################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]
output_folder: !ref results/CRNN/<seed>
wer_file: !ref <output_folder>/wer.txt
save_folder: !ref <output_folder>/save
train_log: !ref <output_folder>/train_log.txt

# Data files
data_folder: datasets/data # e.g. /path/to/TIMIT
uppercase: True
open_rir_folder: !ref <data_folder> # where to store noisy data for augment (change it if needed)
train_annotation: !ref <output_folder>/train.json
valid_annotation: !ref <output_folder>/dev.json
test_annotation: !ref <output_folder>/test.json
skip_prep: True # Skip data preparation

# Training parameters
number_of_epochs: 30
batch_size: 10
lr: 1.0
sorting: ascending # choose between ascending, descending and random

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 40

# Model parameters
# activation: !name:torch.nn.LeakyReLU
# dropout: 0.15
# cnn_blocks: 2
# cnn_channels: (128, 256)
# cnn_kernelsize: (3, 3)
# rnn_layers: 4
# rnn_neurons: 512
# rnn_bidirectional: True
# dnn_blocks: 2
# dnn_neurons: 512

# activation: !name:torch.nn.LeakyReLU
# dropout: 0.15
# cnn_blocks: 2
# cnn_channels: (128, 256)
# cnn_kernelsize: (3, 3)
# rnn_layers: 4
# rnn_neurons: 256
# rnn_bidirectional: True
# dnn_blocks: 2
# dnn_neurons: 256

# Outputs
output_neurons: 40
blank_index: 0

# Dataloader options
train_dataloader_opts:
    batch_size: !ref <batch_size>

valid_dataloader_opts:
    batch_size: !ref <batch_size>

test_dataloader_opts:
    batch_size: !ref <batch_size>

normalize: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    
augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
    sample_rate: !ref <sample_rate>
    speeds: [95, 100, 105]

# Can be removed to improve speed
env_corrupt: !new:speechbrain.lobes.augment.EnvCorrupt
    openrir_folder: !ref <open_rir_folder>
    babble_prob: 0.0
    reverb_prob: 0.0
    noise_prob: 1.0
    noise_snr_low: 0
    noise_snr_high: 15

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

compute_features: !new:speechbrain.lobes.features.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>
    f_max: 8000
    win_length: 20
    hop_length: 160

# model: !new:speechbrain.lobes.models.CRDNN.CRDNN
#     input_size: !ref <n_mels>
#     activation: !ref <activation>
#     dropout: !ref <dropout>
#     cnn_blocks: !ref <cnn_blocks>
#     cnn_channels: !ref <cnn_channels>
#     cnn_kernelsize: !ref <cnn_kernelsize>
#     time_pooling: True
#     rnn_layers: !ref <rnn_layers>
#     rnn_neurons: !ref <rnn_neurons>
#     rnn_bidirectional: !ref <rnn_bidirectional>
#     dnn_blocks: !ref <dnn_blocks>
#     dnn_neurons: !ref <dnn_neurons>

# Model parameters
kernel_size: 3
pool_kernal_size: 2
cnn_emb_channel1: 128
cnn_emb_channel2: 256
cnn_emb_channel2_pool: !ref <cnn_emb_channel2> // <pool_kernal_size>
cnn_emb_channel3: 256
cnn_emb_channel4: 512
# GRU
rnn_input_neurons: !ref <cnn_emb_channel4> // <pool_kernal_size>
rnn_neurons: 1024
num_direction: 2

conv1: !name:speechbrain.nnet.CNN.Conv1d
    out_channels: !ref <cnn_emb_channel1> 
    kernel_size: !ref <kernel_size>
    in_channels: !ref <n_mels>

conv2: !name:speechbrain.nnet.CNN.Conv1d
    out_channels: !ref <cnn_emb_channel2> 
    kernel_size: !ref <kernel_size>
    in_channels: !ref <cnn_emb_channel1>

# pooling: kernal_size = 2, in_channels: 1024 / 2 = 512
conv3: !name:speechbrain.nnet.CNN.Conv1d
    out_channels: !ref <cnn_emb_channel3>
    kernel_size: !ref <kernel_size>
    in_channels: !ref <cnn_emb_channel2_pool>

conv4: !name:speechbrain.nnet.CNN.Conv1d
    out_channels: !ref <cnn_emb_channel4>
    kernel_size: !ref <kernel_size>
    in_channels: !ref <cnn_emb_channel3>

custom_emb_module: !new:speechbrain.nnet.containers.Sequential
    # input_shape: [null, null, !ref <n_fft> // 2 + 1]
    input_shape: [null, null, !ref <n_mels>]
    conv1: !ref <conv1>
    activation1: !new:torch.nn.LeakyReLU
    conv2: !ref <conv2>
    activation2: !new:torch.nn.LeakyReLU
    maxpool1: !new:torch.nn.MaxPool1d
    # maxpool1: !new.speechbrain.nnet.pooling.Pooling1d
        kernel_size: !ref <pool_kernal_size>
    #     pool_type: "max"
    #     input_dims: 4
    #     pool_axis: 2
    conv3: !ref <conv3>
    activation3: !new:torch.nn.LeakyReLU
    conv4: !ref <conv4>
    activation4: !new:torch.nn.LeakyReLU
    maxpool2: !new:torch.nn.MaxPool1d
        kernel_size: !ref <pool_kernal_size>
    # output_size = <cnn_emb_channel4> // 2 = 256

# pooling: kernal_size = 2, in_channels: 512 / 2 = 256
decoder: !new:speechbrain.nnet.RNN.GRU
    hidden_size: !ref <rnn_neurons>
    input_shape: [null, null, !ref <rnn_input_neurons>]
    dropout: 0.1
    bidirectional: True

batchnorm: !new:speechbrain.nnet.normalization.BatchNorm1d
    input_shape: [null, null, !ref <rnn_neurons> * <num_direction>]

linear1: !ref <rnn_neurons> * <num_direction> 
linear2: !ref <linear1> // 2
linear3: !ref <linear2> // 2

output1: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <linear1>
    n_neurons: !ref <linear2>
    bias: True

output2: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <linear2>
    n_neurons: !ref <linear3>
    bias: True

output3: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <linear3>
    n_neurons: !ref <output_neurons>
    bias: True

modules:
    model: !ref <custom_emb_module>
    normalize: !ref <normalize>
    rnn: !ref <decoder>
    batchnorm: !ref <batchnorm>
    dense1: !ref <output1>
    dense2: !ref <output2>
    dense3: !ref <output3>
    env_corrupt: !ref <env_corrupt>

# modules:
    # model: !ref <model>
    # output: !ref <output>
    # normalize: !ref <normalize>
    # env_corrupt: !ref <env_corrupt>

# jit_module_keys: [model]

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

opt_class: !name:torch.optim.Adadelta
    rho: 0.95
    lr: !ref <lr>
    eps: 1.e-8

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        # normalizer: !ref <normalize>
        model: !ref <custom_emb_module>
        rnn: !ref <decoder>
        batchnorm: !ref <batchnorm>
        dense1: !ref <output1>
        dense2: !ref <output2>
        dense3: !ref <output3>
        scheduler: !ref <lr_annealing>
        counter: !ref <epoch_counter>

# checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
#     checkpoints_dir: !ref <save_folder>
#     recoverables:
#         model: !ref <model>
#         output: !ref <output>
#         scheduler: !ref <lr_annealing>
#         normalizer: !ref <normalize>
#         counter: !ref <epoch_counter>

compute_cost: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
    save_file: !ref <train_log>

ctc_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.ctc_loss
        blank_index: !ref <blank_index>
        reduction: batch

per_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats
# bin_stats: !name:speechbrain.utils.metric_stats.BinaryMetricStats
