name: cs7643-mdd
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - numpy
  - pyyaml
  - matplotlib
  - scipy
  - future
  - cudatoolkit=10.2
  - python=3.8
  - pytorch::pytorch
  - pytorch::torchaudio
  - tqdm
  - pip
  - pip:
    - textgrid
    - speechbrain
    - gdown
    - PySoundFile
    - sox